aggregator:
  retention1d: 2
  aggregatorDbStorage:
    storageRequest: 8Gi
  persistentConfigsStorage:
    storageRequest: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 3Gi

localStore:
  retention1d: 2
  persistentVolume:
    enabled: true
    size: 2Gi

finopsagent:
  agent:
    collectorDataSource:
      retention1d: 2

forecasting:
  enabled: false

networkCosts:
  enabled: false

clusterController:
  enabled: false

frontend:
  service:
    type: ClusterIP
