apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: playground-otel
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: otel-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/part-of: otel-stack
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - name: ui
              containerPort: 16686
              protocol: TCP
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: playground-otel
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: otel-stack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
      protocol: TCP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
